package interfaz;

import matrices.Matriz;
import java.util.ArrayList;

public class MenuMatrices extends javax.swing.JFrame {

    private Matriz matrizEditada;
    private int dimensionFilas;
    private int dimensionColumnas;
    private int filaActual;
    private int columnaActual;
    private Menu menuCorrespondiente;
    
    /**
     * Creates new form MenuMatrices
     */
    public MenuMatrices(Matriz matrizAEditar, Menu menu) {
        initComponents();
        menuCorrespondiente = menu;
        cargarMatriz(matrizAEditar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        selectorFilas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        selectorColumnas = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visualizadorMatriz = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        selectorValor = new javax.swing.JSpinner();
        arribaBoton = new javax.swing.JButton();
        abajoBoton = new javax.swing.JButton();
        derechaBoton = new javax.swing.JButton();
        izquierdaBoton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        seleccionBoton = new javax.swing.JButton();
        labelFila = new javax.swing.JLabel();
        labelColumna = new javax.swing.JLabel();
        aplicarBoton = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setText("EDITANDO MATRIZ A");

        selectorFilas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel1.setText("Filas");

        selectorColumnas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setText("Columnas");

        visualizadorMatriz.setEditable(false);
        visualizadorMatriz.setColumns(20);
        visualizadorMatriz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        visualizadorMatriz.setRows(5);
        jScrollPane1.setViewportView(visualizadorMatriz);

        jLabel3.setText("Elemento Seleccionado");

        selectorValor.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        arribaBoton.setText("^");
        arribaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arribaBotonActionPerformed(evt);
            }
        });

        abajoBoton.setText("v");
        abajoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abajoBotonActionPerformed(evt);
            }
        });

        derechaBoton.setText(">");
        derechaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaBotonActionPerformed(evt);
            }
        });

        izquierdaBoton.setText("<");
        izquierdaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaBotonActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor Actual");

        seleccionBoton.setText("O");
        seleccionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionBotonActionPerformed(evt);
            }
        });

        labelFila.setText("Fila Actual: 0");

        labelColumna.setText("Columna Actual: 0");

        aplicarBoton.setText("APLICAR");
        aplicarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarBotonActionPerformed(evt);
            }
        });

        actualizar.setText("ACTUALIZAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(selectorValor, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(selectorFilas)
                                    .addComponent(selectorColumnas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(aplicarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(izquierdaBoton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(seleccionBoton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(derechaBoton))
                                            .addComponent(abajoBoton)
                                            .addComponent(arribaBoton)))
                                    .addComponent(jLabel3)
                                    .addComponent(labelFila)
                                    .addComponent(labelColumna))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectorFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectorColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizar)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectorValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelColumna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arribaBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(izquierdaBoton)
                            .addComponent(seleccionBoton)
                            .addComponent(derechaBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abajoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(aplicarBoton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarBotonActionPerformed
        // TODO add your handling code here:
        menuCorrespondiente.guardarCambiosMatriz();
        this.dispose();
    }//GEN-LAST:event_aplicarBotonActionPerformed

    private void arribaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arribaBotonActionPerformed
        // TODO add your handling code here:
        if (filaActual > 0)
        {
            filaActual--;
        }
        actualizarMatriz();
    }//GEN-LAST:event_arribaBotonActionPerformed

    private void abajoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abajoBotonActionPerformed
        // TODO add your handling code here:
        if (filaActual < matrizEditada.getFilas()-1)
        {
            filaActual++;
        }
        actualizarMatriz();
    }//GEN-LAST:event_abajoBotonActionPerformed

    private void derechaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaBotonActionPerformed
        // TODO add your handling code here:
        if (columnaActual < matrizEditada.getColumnas()-1)
        {
            columnaActual++;
        }
        actualizarMatriz();
    }//GEN-LAST:event_derechaBotonActionPerformed

    private void izquierdaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaBotonActionPerformed
        // TODO add your handling code here:
        if (columnaActual > 0)
        {
            columnaActual--;
        }
        actualizarMatriz();
    }//GEN-LAST:event_izquierdaBotonActionPerformed

    private void seleccionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionBotonActionPerformed
        // TODO add your handling code here:
        matrizEditada.setElemento(filaActual, columnaActual, (float)selectorValor.getValue());
        actualizarMatriz();
    }//GEN-LAST:event_seleccionBotonActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        actualizarMatriz();
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuMatrices().setVisible(true);
            }
        });
    }
    
    private void cargarMatriz(Matriz matriz)
    {
        matrizEditada = matriz;
        
        filaActual = 0;
        columnaActual = 0;
        
        titulo.setText("EDITANDO MATRIZ "+matrizEditada.getId());
        selectorFilas.setValue(matrizEditada.getFilas());
        selectorColumnas.setValue(matrizEditada.getColumnas());
        selectorValor.setValue(matrizEditada.getElemento(filaActual, columnaActual));
        
        dimensionFilas = matrizEditada.getFilas();
        dimensionColumnas = matrizEditada.getColumnas();
        
        labelFila.setText("Fila actual: "+filaActual);
        labelColumna.setText("Columna actual: "+columnaActual);
        
        mostrarMatriz(matrizEditada);
    }
    
    private void actualizarMatriz()
    {   
        mostrarMatriz(matrizEditada);
        
        if (dimensionFilas != (int)selectorFilas.getValue() || 
            dimensionColumnas != (int)selectorColumnas.getValue())
        {
            matrizEditada = new Matriz((int)selectorFilas.getValue(), 
                                       (int)selectorColumnas.getValue(), 
                                        matrizEditada.getId());
            cargarMatriz(matrizEditada);
        }
        
        selectorValor.setValue(matrizEditada.getElemento(filaActual, columnaActual));

        labelFila.setText("Fila actual: "+filaActual);
        labelColumna.setText("Columna actual: "+columnaActual);
    }
    
    private void mostrarMatriz(Matriz matriz)
    {
        visualizadorMatriz.setText("");
        ArrayList<String> visualizacion = matriz.mostrarElemento(filaActual, columnaActual);
        for (int i = 0; i < visualizacion.size(); i++)
        {
            visualizadorMatriz.setText(visualizadorMatriz.getText() + visualizacion.get(i));
        }
    }
    
    public Matriz getMatriz()
    {
        return matrizEditada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abajoBoton;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton aplicarBoton;
    private javax.swing.JButton arribaBoton;
    private javax.swing.JButton derechaBoton;
    private javax.swing.JButton izquierdaBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelColumna;
    private javax.swing.JLabel labelFila;
    private javax.swing.JButton seleccionBoton;
    private javax.swing.JSpinner selectorColumnas;
    private javax.swing.JSpinner selectorFilas;
    private javax.swing.JSpinner selectorValor;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea visualizadorMatriz;
    // End of variables declaration//GEN-END:variables
}
