import java.util.ArrayList;
import javax.swing.JFrame;

public class Menu extends javax.swing.JFrame {
    
    private Matriz matrizA = new Matriz(3,3,"A");
    private Matriz matrizB = new Matriz(3,3,"B");
    private Matriz matrizC = new Matriz(3,3,"C");
    private Matriz matrizD = new Matriz(3,3,"D");
    private Matriz matrizE = new Matriz(3,3,"E");
    private Matriz matrizF = new Matriz(3,3,"F");
    private Matriz matrizG = new Matriz(3,3,"G");
    private Matriz matrizH = new Matriz(3,3,"H");
    
    private MenuMatrices menuEditarMatrices;
    private ManipuladorMatrices manipuladorMatrices = new ManipuladorMatrices();
    
    /**
     * Creates new form MainMenu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        editarMatrizBoton = new javax.swing.JButton();
        selectorMatriz = new javax.swing.JComboBox<>();
        selectorProcedimiento = new javax.swing.JComboBox<>();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        selectorMatriz1 = new javax.swing.JComboBox<>();
        selectorMatriz2 = new javax.swing.JComboBox<>();
        titulo3 = new javax.swing.JLabel();
        calcularBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visualizadorMatriz = new javax.swing.JTextArea();
        selectorEscalar = new javax.swing.JSpinner();
        labelEscalar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setText("CALCULADORA MATRICES");

        editarMatrizBoton.setText("Editar");
        editarMatrizBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMatrizBotonActionPerformed(evt);
            }
        });

        selectorMatriz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));

        selectorProcedimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma de dos matrices", "Multiplicacion entre dos matrices", "Multiplicacion por Escalar", "Transpuesta de Matriz", "Inversa de Matriz por Gauss-Jordan", "Solucion Sistema de Ecuaciones por Gauss-Jordan" }));

        titulo1.setText("SELECCIONE MATRIZ PARA EDITAR");

        titulo2.setText("ESCOGER OPERACION");

        selectorMatriz1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));

        selectorMatriz2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));

        titulo3.setText("RESULTADO");

        calcularBoton.setText("CALCULAR");
        calcularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBotonActionPerformed(evt);
            }
        });

        visualizadorMatriz.setEditable(false);
        visualizadorMatriz.setColumns(20);
        visualizadorMatriz.setRows(5);
        jScrollPane1.setViewportView(visualizadorMatriz);

        selectorEscalar.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        labelEscalar.setText("Escalar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(titulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectorMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarMatrizBoton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(selectorMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(selectorMatriz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelEscalar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(selectorEscalar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(calcularBoton))
                                .addComponent(selectorProcedimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarMatrizBoton)
                    .addComponent(selectorMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorMatriz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularBoton)
                    .addComponent(selectorEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEscalar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarMatrizBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMatrizBotonActionPerformed
        // TODO add your handling code here:
        Matriz matrizSeleccionada = obtenerMatrizDeSeleccion(selectorMatriz);
        
        menuEditarMatrices = new MenuMatrices(matrizSeleccionada, this);
        menuEditarMatrices.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        menuEditarMatrices.setVisible(true);
    }//GEN-LAST:event_editarMatrizBotonActionPerformed

    private void calcularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBotonActionPerformed
        // TODO add your handling code here:
        Matriz matrizSeleccionada1 = obtenerMatrizDeSeleccion(selectorMatriz1);
        Matriz matrizSeleccionada2 = obtenerMatrizDeSeleccion(selectorMatriz2);
        
        Object[] parametros = new Object[3];
        parametros[0] = matrizSeleccionada1;
        parametros[1] = matrizSeleccionada2;
        parametros[2] = (float)selectorEscalar.getValue();
        
        Matriz resultado = procedimientoDeSeleccion(selectorProcedimiento, parametros);
        mostrarMatriz(resultado);
    }//GEN-LAST:event_calcularBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private Matriz obtenerMatrizDeSeleccion(javax.swing.JComboBox<String> seleccion)
    {
        //System.out.println(seleccion.getSelectedItem().toString());
        switch(seleccion.getSelectedItem().toString())
        {
            case "A":
                return this.matrizA;
            case "B":
                return this.matrizB;
            case "C":
                return this.matrizC;
            case "D":
                return this.matrizD;
            case "E":
                return this.matrizE;
            case "F":
                return this.matrizF;
            case "G":
                return this.matrizG;
            case "H":
                return this.matrizH;
            default:
                return null;
        }
    }
    
    private Matriz procedimientoDeSeleccion(javax.swing.JComboBox<String> seleccion, Object[] parametros)
    {
        //System.out.println(seleccion.getSelectedItem().toString());
        switch(seleccion.getSelectedItem().toString())
        {
            case "Suma de dos matrices":
                return manipuladorMatrices.sumaEntreMatrices((Matriz)parametros[0], (Matriz)parametros[1]);
            case "Multiplicacion entre dos matrices":
                return manipuladorMatrices.productoEntreMatrices((Matriz)parametros[0], (Matriz)parametros[1]);
            case "Multiplicacion por Escalar":
                return manipuladorMatrices.multiplicacionPorEscalar((Matriz)parametros[0], (float)parametros[2]);
            case "Transpuesta de Matriz":
                return manipuladorMatrices.calcularTranspuesta((Matriz)parametros[0]);
            case "Inversa de Matriz por Gauss-Jordan":
                //return manipuladorMatrices.calcularInversaGaussJordan((Matriz)parametros[0]);
            case "Solucion Sistema de Ecuaciones por Gauss-Jordan":
                //return manipuladorMatrices.solucionarSistemaGaussJordan((Matriz)parametros[0]);
            default:
                return null;
        }
    }
    
    public void guardarCambios()
    {
        Matriz guardado = menuEditarMatrices.getMatriz();
        
        switch(guardado.getId())
        {
            case "A":
                matrizA = guardado;
                break;
            case "B":
                matrizB = guardado;
                break;
            case "C":
                matrizC = guardado;
                break;
            case "D":
                matrizD = guardado;
                break;
            case "E":
                matrizE = guardado;
                break;
            case "F":
                matrizF = guardado;
                break;
            case "G":
                matrizG = guardado;
                break;
            case "H":
                matrizH = guardado;
                break;
        }
    }
    
    private void mostrarMatriz(Matriz matriz)
    {
        visualizadorMatriz.setText("");
        ArrayList<String> visualizacion = matriz.mostrarElemento(-1, -1);
        for (int i = 0; i < visualizacion.size(); i++)
        {
            visualizadorMatriz.setText(visualizadorMatriz.getText() + visualizacion.get(i));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularBoton;
    private javax.swing.JButton editarMatrizBoton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEscalar;
    private javax.swing.JSpinner selectorEscalar;
    private javax.swing.JComboBox<String> selectorMatriz;
    private javax.swing.JComboBox<String> selectorMatriz1;
    private javax.swing.JComboBox<String> selectorMatriz2;
    private javax.swing.JComboBox<String> selectorProcedimiento;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JTextArea visualizadorMatriz;
    // End of variables declaration//GEN-END:variables
}
